/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'

// Create Virtual Routes

const Index2LazyImport = createFileRoute('/index2')()
const AboutLazyImport = createFileRoute('/about')()
const R72outeLazyImport = createFileRoute('/%72oute')()
const IndexLazyImport = createFileRoute('/')()
const BarBazLazyImport = createFileRoute('/bar/baz')()
const AboutFooLazyImport = createFileRoute('/about/foo')()

// Create/Update Routes

const Index2LazyRoute = Index2LazyImport.update({
  path: '/index2',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index2.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const R72outeLazyRoute = R72outeLazyImport.update({
  path: '/%72oute',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/%72oute.lazy').then((d) => d.Route))

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const BarBazLazyRoute = BarBazLazyImport.update({
  path: '/bar/baz',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bar/baz.lazy').then((d) => d.Route))

const AboutFooLazyRoute = AboutFooLazyImport.update({
  path: '/foo',
  getParentRoute: () => AboutLazyRoute,
} as any).lazy(() => import('./routes/about/foo.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/%72oute': {
      id: '/%72oute'
      path: '/%72oute'
      fullPath: '/%72oute'
      preLoaderRoute: typeof R72outeLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/index2': {
      id: '/index2'
      path: '/index2'
      fullPath: '/index2'
      preLoaderRoute: typeof Index2LazyImport
      parentRoute: typeof rootRoute
    }
    '/about/foo': {
      id: '/about/foo'
      path: '/foo'
      fullPath: '/about/foo'
      preLoaderRoute: typeof AboutFooLazyImport
      parentRoute: typeof AboutLazyImport
    }
    '/bar/baz': {
      id: '/bar/baz'
      path: '/bar/baz'
      fullPath: '/bar/baz'
      preLoaderRoute: typeof BarBazLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  R72outeLazyRoute,
  AboutLazyRoute: AboutLazyRoute.addChildren({ AboutFooLazyRoute }),
  Index2LazyRoute,
  BarBazLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/%72oute",
        "/about",
        "/index2",
        "/bar/baz"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx"
    },
    "/%72oute": {
      "filePath": "%72oute.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx",
      "children": [
        "/about/foo"
      ]
    },
    "/index2": {
      "filePath": "index2.lazy.tsx"
    },
    "/about/foo": {
      "filePath": "about/foo.lazy.tsx",
      "parent": "/about"
    },
    "/bar/baz": {
      "filePath": "bar/baz.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
